graph LR
    InProgress -->|to_update| changesRequired
    changesRequired -->|to_update| InProgress
    InProgress -->|to_complete| PendingRiskAnalysis
    PendingRiskAnalysis -->|to_accept_risk| PendingSignatures
    PendingRiskAnalysis -->|to_require_changes| changesRequired
    PendingRiskAnalysis -->|to_reject| Rejected
    PendingSignatures -->|to_sign| SignReview
    SignReview -->|to_reject_signed| RejectedSigned
    SignReview -->|to_approve| Approved
    SignReview -->|to_sign| ChangeRequestedPostSigning
    ChangeRequestedPostSigning -->|to_restart| InProgress
